const FileSystemActionTypes = {
  UPLOAD_FILE_START: "UPLOAD_FILE_START",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

  DOWNLOAD_DATA_START: "DOWNLOAD_DATA_START",
  DOWNLOAD_DATA_SUCCESS: "DOWNLOAD_DATA_SUCCESS",
  DOWNLOAD_DATA_FAILURE: "DOWNLOAD_DATA_FAILURE",
};

export default FileSystemActionTypes;
